### ISSUE TITLE
Primera estructura de clases/ficheros PHP

### ISSUE THREAD

**Issue by faparraf** [udistrital/autenticacion_mid#1]
La organización busca tener una primera plantilla o estructura de las clases que se implementarán con el fin de usar un flujo OIDC mediante **udistrital/oidc-auth-js** de npm y adaptar dicho flujo al manejo de sesiones en _SARA_ en PHP con el fin de iniciar el acoplamiento de la autenticación única en PHP.

**Criterios de Aceptación:**
- [x] Visto bueno de @udistrital/administrativa 
- [x] Código en rama _default_

**Comment by jdc996** [comment]
Se agrega el enlace a la clase php para el manejo de flujo OIDC para implementar autenticacion unica
https://drive.google.com/drive/u/1/folders/1lfLg_Fwbe8sA6nkz2wAGe17EOFFn_LCH
