### ISSUE TITLE
Implementación inicial de clase PHP para autenticación OIDC

### ISSUE THREAD

**Issue by faparraf** [udistrital/autenticacion_mid#2]
La organización requiere el inicio de la implementación de las clases de autenticación con el fin de ejecutar pruebas sobre el funcionamiento del flujo OICD en las aplicaciones desarrolladas en PHP. Se busca entonces **evidencias** de la implementación de dichas clases en ambientes similares a los ejecutados en producción.

**Criterios de aceptación**
- [ ] Implementación de las clases evidenciadas en la aplicación escogida para tal fin.
- [ ] Primeras implementaciones de la  librería OIDC JS que se desarrolla en paralelo

**Comment by jdc996** [comment]
Se realiza la implementacion de la libreria de autenticacion en su primera version utilizando ES6

**Comment by OscarDuarte7** [comment]
Se implementó en una clase de php con el login de WSO2, guardando de momento en el localStorage.

**Comment by jdc996** [comment]
Se implementa login y logout en la clase php con WSO2
https://drive.google.com/drive/u/1/folders/1lfLg_Fwbe8sA6nkz2wAGe17EOFFn_LCH
