### ISSUE TITLE
Análisis de información compartida entre SIDEAP y AGORA.

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#24]
Se requiere realizar el análisis de información compartida entre el sistema AGORA y el sistema externo SIDEAP.

**Criterios de aceptación**

- [x] Documento con variables en comun entre los sistemas mencionados.

**Material de apoyo**

- https://docs.google.com/spreadsheets/d/1q94p70_t46GpJ2eKVlBDFGRDWFxKCGMMclIWWCT-kjc/edit?usp=sharing

**Nota:** se recuerda que la información que se busca conectar es la solicitada en el proceso de contratación.

**Comment by iMrJulian** [comment]
Análisis de las variables de los sistemas Sigeap y Agora

V1: https://docs.google.com/spreadsheets/d/1eqpYPr9vXSheR2FFae7PpNySnv2Bsq9AMPK3bc5_ilk/edit?usp=sharing

**Comment by iMrJulian** [comment]
Análisis de las variables de los sistemas Sigeap y Agora

V2: https://docs.google.com/spreadsheets/d/1eqpYPr9vXSheR2FFae7PpNySnv2Bsq9AMPK3bc5_ilk/edit?usp=sharing

**Comment by a52290451** [comment]
Se revisa y aprueba documento con variables en comun entre los sistemas mencionados.
