### ISSUE TITLE
Comunicación con SIDEAP

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#25]
Se requiere establecer comunicación con SIDEAP a través de correo electrónico para concretar una reunión que permita iniciar un proceso de interoperabilidad con los sistemas de la Oficina Asesora de Sistemas.

**Criterios de aceptación**

- [x] Buscar posibles correos de contacto con SIDEAP.
- [x] Redacción del mensaje a enviar (el mensaje debe contener la información que queremos obtener de SIDEAP)

**Comment by iMrJulian** [comment]
Posibles correos de contacto:

sideap@serviciocivil.gov.co
contacto@serviciocivil.gov.co
eva@funcionpublica.gov.co

**Comment by iMrJulian** [comment]
Buen día,

Reciban un cordial saludo SIDEAP.

Actualmente dentro de la Oficina Asesora de Sistemas (OAS) de la Universidad Distrital Francisco José de Caldas se tiene como objetivo optimizar los procesos institucionales usando sistemas computacionales capaces de interoperar con sistemas de fuentes tanto internas como externas. Dentro de dichos procesos, algunos están relacionados con la contratación y la gestión del personal.

Es por esto que realizamos un análisis del sistema de los datos que son utilizados para la creación, edición, presentación y validación de la hoja de vida, entendiendo este como un proceso necesario de contratación y gestión del personal de la universidad, dentro de este análisis se encontraron al menos 26 variables en común con uno de nuestros sistemas internos llamado Ágora en materia de datos básicos, datos de nacimiento, datos de contacto, ubicación de residencia, datos complementarios y condiciones medicas especiales. 

Sin embargo, encontramos que los datos son necesarios para la generación y validación de la hoja de vida son indispensables para interoperar con otros sistemas internos, es por eso que estamos interesados en dar un trato más sistémico sobre la información interna de éste tipo, y quisiéramos obtener acceso a algún servicio capaz de tratar la información almacenada en el SIDEAP con el fin de automatizar el tratado y la actualización de dicha información. Con el fin de lograr interoperar con ustedes para evitar que los datos se repliquen y que exista incongruencias, por el contrario, que la información sea transversal entre los sistemas involucrados .

Nos gustaría realizar una reunión con ustedes para comunicar con más detalle los planes que se manejan en la OAS con respecto a sistemas externos y conocer un poco más acerca de SIDEAP.

Adicionalmente adjuntamos el análisis de los datos encontrados en SIDEAP.

Muchas gracias y quedamos atentos a su respuesta.

Cordialmente,

**Comment by a52290451** [comment]
Se realiza envio de correo para contactar con SIDEAP.

**Comment by a52290451** [comment]
Se recibe el siguiente comunicado:

Se informa que su solicitud ha sido radicada con el número: 1-2022-7492
Tenga en cuenta que para verificar el estado de la radicación se solicitará el siguiente código: 661b8462-36ac-4369-a8c8-099defb1e3c3.

Para hacer seguimiento ingrese aquí:https://siga.serviciocivil.gov.co/WebSigaPQR/#!/consultaPQR


 Este es un mensaje automático, por favor no lo responda.
 
 
![image](https://user-images.githubusercontent.com/36229498/194402770-23382dd8-6b6f-4fc3-8428-47e7510d269d.png)

**Comment by a52290451** [comment]
Se realiza consulta del estado en el que se encuentra la solicitud el 18 de octubre.

Reporte: la solicitud no presenta novedades.

**Comment by a52290451** [comment]
Desde la Oficina Asesora de Sistemas, comunican lo siguiente:

"Vía telefónica se recibe comunicación con el funcionario Fernando Montero y plantea que se cuadre la reunión para encontrar si es viable lo que le expresan mediante este correo, que se puede comunicar con él al número 305-705-8460 "

**Comment by a52290451** [comment]
Se presenta el siguiente documento como respuesta a la solicitud realizada
[2-2022-9106_1.pdf](https://github.com/udistrital/autenticacion_mid/files/9832701/2-2022-9106_1.pdf)
Queda pendiente elegir fecha, agendar reunión y dar respuesta a comunicado.

**Comment by a52290451** [comment]
Se realiza reunión exploratoria con SIDEAP el Jueves 03 de Noviembre de 2022 -

**Comment by a52290451** [comment]
Se envia correo con material de apoyo el 09 de Noviembre de 2022 - 
[Correo de Universidad Distrital Francisco José de Caldas - Material de apoyo - Interoperabilidad con sistemas externos - Oficina Asesora de Sistemas - UD.pdf](https://github.com/udistrital/autenticacion_mid/files/9972946/Correo.de.Universidad.Distrital.Francisco.Jose.de.Caldas.-.Material.de.apoyo.-.Interoperabilidad.con.sistemas.externos.-.Oficina.Asesora.de.Sistemas.-.UD.pdf)
