### ISSUE TITLE
Análisis de información compartida entre parafiscales (Miplanilla.com y AportesEnLinea) y Cumplidos.

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#26]
Se requiere realizar el análisis de información compartida entre parafiscales (Miplanilla.com y AportesEnLinea) y Cumplidos.

**Criterios de aceptación**

- [x] Documento con variables o información en comun entre los sistemas mencionados.

Material de apoyo

- https://docs.google.com/spreadsheets/d/1q94p70_t46GpJ2eKVlBDFGRDWFxKCGMMclIWWCT-kjc/edit?usp=sharing

**Nota:** tener en cuenta que se busca información que permita verificar que el contratista realizó sus aportes a parafiscales y prestaciones sociales, con los porcentajes adecuados.

**Comment by iMrJulian** [comment]
Simplificación y separación del análisis de variables en común entre parafiscales y sistemas de la universidad distrital (Cumplidos y Titan) 

Aportes en línea
V1.2: https://docs.google.com/spreadsheets/d/1PwF7dzEb_kCeV_UDbGiShNjSjpL0-vCd7_xd4mV5-go/edit?usp=sharing

MiPlanilla
V1.2 https://docs.google.com/spreadsheets/d/1K-N-hrAFGYssAw_mvu-orGJWocJ8vcgBd2I5nk3TJYs/edit?usp=sharing
