### ISSUE TITLE
Comunicación con parafiscales (Miplanilla.com y AportesEnLinea)

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#27]
Se requiere establecer comunicación con Miplanilla.com y AportesEnLinea a través de correo electrónico para concretar una reunión que permita iniciar un proceso de interoperabilidad con los sistemas de la Oficina Asesora de Sistemas.

**Criterios de aceptación**

- [x] Buscar posibles correos de contacto con Miplanilla.com y AportesEnLinea.
- [x] Redacción del mensaje a enviar (el mensaje debe contener la información que queremos obtener de Miplanilla.com y AportesEnLinea)

**Comment by iMrJulian** [comment]
CORREO MIPLANILLA

CONTACTO
- https://www.miplanilla.com/Contacto/Contacto
- [miplanilla@miplanilla.com](mailto:miplanilla@miplanilla.com)
- [operadorpila@compensar.com](mailto:operadorpila@compensar.com)

Buen día,

Reciban un cordial saludo,
MiPlanilla
Compensar

Actualmente dentro de la Oficina Asesora de Sistemas (OAS) de la Universidad Distrital Francisco José de Caldas se tiene como objetivo optimizar los procesos institucionales usando sistemas computacionales capaces de interoperar con sistemas de fuentes tanto internas como externas. Dentro de dichos procesos, algunos están relacionados con los aportes obligatorios realizados por los contratistas en cuanto a salud, pensión y ARL.

Es por eso que estamos interesados en dar un trato más sistémico en la verificación del pago de aportes obligatorios y la información interna de éste tipo. Para ello, realizamos un análisis previo de las variables que son utilizadas en su sistema para llevar a cabo el proceso, encontrado variables en común la información básica del contratista como:

- Tipo de documento
- Numero de documento
- Nombre
- Correo electrónico
- Celular
- Teléfono fijo

Así como información sobre el aporte entre ella:

- Ingresos mensuales
- Base de cotización
- Aporte de pensión 
- Aporte a salud
- Aporte a ARL
- Periodo
- Comprobante de pago

Quisiéramos logar un vinculo de acceso a algún servicio capaz de brindar la información almacenada de nuestros contratistas en materia de aportes obligatorios, con el fin de automatizar el tratado y la actualización de dicha información. Nuestro objetivo es lograr interoperar con ustedes a fin de que la información tratada no se replique, por el contrario, que sea transversal entre los sistemas involucrados. 

De esta forma, nos gustaría realizar una reunión con ustedes para comunicar con más detalle los planes que se manejan en la OAS con respecto a sistemas externos y conocer un poco más acerca de MiPlanilla.

Adicionalmente adjuntamos un archivo excel, en el cual se realizo un análisis de las posibles variables en común que maneja sus sistemas con los nuestros, variables de gran utilidad en el proceso de interoperar entre las plataformas.

Muchas gracias y quedamos atentos a sus comentarios.

Cordialmente,

**Comment by iMrJulian** [comment]
CORREO APORTES EN LÍNEA

CONTACTO
- https://www.aportesenlinea.com/Home/Contacto.aspx#
- [protecciondedatos@aportesenlinea.com](mailto:protecciondedatos@aportesenlinea.com)
- [informacion@email-aportesenlinea.com](mailto:informacion@email-aportesenlinea.com)
- [agente_aportesenlinea@email-aportesenlinea.com](mailto:agente_aportesenlinea@email-aportesenlinea.com)

Buen día,

Reciban un cordial saludo,
Aportes en Línea

Actualmente dentro de la Oficina Asesora de Sistemas (OAS) de la Universidad Distrital Francisco José de Caldas se tiene como objetivo optimizar los procesos institucionales usando sistemas computacionales capaces de interoperar con sistemas de fuentes tanto internas como externas. Dentro de dichos procesos, algunos están relacionados con los aportes obligatorios realizados por los contratistas en cuanto a salud, pensión y ARL.

Es por eso que estamos interesados en dar un trato más sistémico en la verificación del pago de aportes obligatorios y la información interna de éste tipo, Para ello, realizamos un análisis previo de las variables que son utilizadas en su sistema para llevar a cabo el proceso, encontrado variables en común la información básica del contratista como:

- Tipo de documento
- Numero de documento
- Nombre
- Correo electrónico
- Celular
- Teléfono fijo

Así como información sobre el aporte entre ella:
- Ingresos mensuales
- Base de cotización
- Aporte de pensión 
- Aporte a salud
- Aporte a ARL
- Periodo
- Comprobante de pago

Quisiéramos logar un vinculo de acceso a algún servicio capaz de brindar la información almacenada de nuestros contratistas en materia de aportes obligatorios, con el fin de automatizar el tratado y la actualización de dicha información. Nuestro objetivo es lograr interoperar con ustedes a fin de que la información tratada no se replique, por el contrario, que sea transversal entre los sistemas involucrados. 

De esta forma, nos gustaría realizar una reunión con ustedes para comunicar con más detalle los planes que se manejan en la OAS con respecto a sistemas externos y conocer un poco más acerca de Aportes en Línea.

Adicionalmente adjuntamos un archivo excel, en el cual se realizo un análisis de las posibles variables en común que maneja sus sistemas con los nuestros, variables de gran utilidad en el proceso de interoperar entre las plataformas.

Muchas gracias y quedamos atentos a sus comentarios.

Cordialmente,

[Variables en común AportesEnLinea y sistemas UDistrital.xlsx](https://github.com/udistrital/autenticacion_mid/files/9726586/Variables.en.comun.AportesEnLinea.y.sistemas.UDistrital.xlsx)

**Comment by a52290451** [comment]
Se realiza envio de correos para contactar con sistemas externos.

**Comment by a52290451** [comment]
Se registra contestación por parte de AportesEnLinea
![image](https://user-images.githubusercontent.com/36229498/194644063-8b1cef6a-1939-4b7f-a3fb-4326bf743398.png)

**Comment by a52290451** [comment]
El día 18 de octubre se realiza seguimiento a la solicitud realizada.
![image (10)](https://user-images.githubusercontent.com/36229498/196558671-fb26a3e2-1c1d-4c91-b25c-8603ec1a7c82.png)

La solicitud ya se encuentra cerrada, por lo que se deduce que esta ya fue atendida. Se solicita a soporte de primer nivel la respuesta emitida.

**Comment by a52290451** [comment]
Se envia nuevamente correo a AportesEnLinea y retoman el caso con un nuevo numero de caso
[Correo de Universidad Distrital Francisco José de Caldas - Fwd_ Incidente_ 221026-007143.pdf](https://github.com/udistrital/autenticacion_mid/files/9881163/Correo.de.Universidad.Distrital.Francisco.Jose.de.Caldas.-.Fwd_.Incidente_.221026-007143.pdf)

**Comment by a52290451** [comment]
Se consulta solicitud el 27 de octubre y esta se encuentra pendiente.

![image](https://user-images.githubusercontent.com/36229498/198341841-d661634b-409a-4149-9ddf-6fec9368e3eb.png)

**Comment by a52290451** [comment]
El día 28 de octubre, se da primera respuesta a la solicitud.

![image](https://user-images.githubusercontent.com/36229498/198705925-8af9f334-c76b-4348-a680-b33895ef285c.png)

**Comment by a52290451** [comment]
Tambien se da la siguiente respuesta:

![image](https://user-images.githubusercontent.com/36229498/198706358-761b9daf-1441-430a-8f24-8ec3fb14df89.png)

Quedamos a la espera de la atención real del caso.

**Comment by a52290451** [comment]
Se realiza verificación del caso número 221026-007143 el cual aparecer solucionado el día 31 de Octubre de 2022.

![image](https://user-images.githubusercontent.com/36229498/199287545-2cc57af4-d91f-47d5-9bf0-f0390dd37d88.png)

Sin embargo, al consultar con la OAS, no aparece contestación de la solicitud:

![image](https://user-images.githubusercontent.com/36229498/199287674-e459c95a-7d93-4f06-b887-a0ee98e31765.png)

**Comment by a52290451** [comment]
Se establece contacto nuevamente con MiPlanilla.com a través del sistema de contacto PQRS:

![image](https://user-images.githubusercontent.com/36229498/205685896-7dcbb7c0-932c-4186-88a0-181020a3b16f.png)
[Interoperabilidad entre sistemas.pdf](https://github.com/udistrital/autenticacion_mid/files/10155846/Interoperabilidad.entre.sistemas.pdf)
