### ISSUE TITLE
Análisis preliminar de formatos y formas para registrar conexiones entre APIs.

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#29]
Se requiere presentar alternativas de solución para lograr registrar las conexiones que existen entre las APIs de la OAS de forma eficiente, permitiendo identificar rapidamente que conexiones tiene una API determinada.

**Criterios de aceptación**

- [ ] Formatos y/o sistemas alternativos que permitan registrar de forma eficiente dicha información.

**Comment by iMrJulian** [comment]
Se realizo un análisis de las alternativas que se tiene para la registración de mapas de conexión que se tiene sobre las APIS depreciadas 

V1: https://docs.google.com/presentation/d/1relA1pkwwnHWgLBl1lQRFPek0g3Gq7xnKkrrfkGMF2w/edit?usp=sharing

**Comment by a52290451** [comment]
Se aprueba formato para registro de conexiones por cada API y solución mediante Python para mapa de conexiones entre APIs.
