### ISSUE TITLE
Implementación completa de clase PHP para OIDC

### ISSUE THREAD

**Issue by faparraf** [udistrital/autenticacion_mid#3]
La organiganización necesita una clase PHP implementable en el framework SARA con la que se pueda hacer uso de la librería JS implementada para el flujo **OIDC**, con el fin de ejecutar dicho flujo en las aplicaciones legadas sin interrumpir el manejo de sesiones interno.

**Entregables:**
- [ ] Implementación de la clase en ambientes locales de SARA
- [x] Clase publicada en el medio determinado para tal fin

**Comment by jdc996** [comment]
Se agrega funcionalidad para traer el idToken y el accesstoken desde la clase de php, se agrega una constante para permitir que se haga la redireccion del logueo a WSO2 de manera directa o en caso contrario se muestre un boton de login, que se encargue de redirigir 
https://drive.google.com/drive/u/0/folders/1lfLg_Fwbe8sA6nkz2wAGe17EOFFn_LCH
