### ISSUE TITLE
Apropición de generalidades - SygmaJS y Python - migración de funcionalidades en APIs Deprecadas

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#30]
Se requiere realizar ejemplos de funcionamiento en las soluciones asocidads a SygmaJS y Python de forma que se pueda identificar cual brinda mejores recursos para análisis y planeación.

**Criterios de aceptación**

- [x] Archivos con soluciones implementadas.

**Comment by iMrJulian** [comment]
Se hizo una apropiación de las herramientas encontrando a python como la mejor opción por su facilidad con el manejo de datos.

En el siguiente repositorio se encuentran el ejemplo en cuestión con su respectivo readme para la facilidad de ejecución
https://github.com/iMrJulian/Ejemplo_Bokeh_Networkx/
