### ISSUE TITLE
Completar formato excel de conexiones por API para oikos_crud_api, core y administrativa_jbpm

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#32]
Se requiere crear y completar el formato de conexiones de cada API a ser depreciada, tomando como referencia el formato estandar ubicado en #29.

**Criterios de aceptación**

- [x] Catalogo de conexiones por API.

**Nota**

Se requiere tener acceso a repositorio de almacenamiento de variables de entorno para identificar la conexión presente entre APIs

**Comment by a52290451** [comment]
El día 14 de octubre de 2022 se solicita acceso al repositorio https://gitlab.com/unidistrital/microservicios en modo lectura.

**Comment by a52290451** [comment]
El día martes 18 de octubre se da acceso a repositorio de variables de entorno.

**Comment by iMrJulian** [comment]
Se realizo un análisis de los servicios que ofrece cada una de las apis, y que apis consumen estos servicios junto con información especifica de donde esta siendo consumida

V1: https://docs.google.com/spreadsheets/d/14mORmhV7_eAZ8xB1XN02JPl_e6dieH6aWk6gwDB1BMo/edit?usp=sharing

**Comment by a52290451** [comment]
Modificación requerida:

1. Los campos de Links deben ser:

Pruebas: pruebasapi...
Producción: api...
Autenticación: autenticacion...
Repositorio: git...

![image](https://user-images.githubusercontent.com/36229498/197254825-8be8f030-1ede-409f-8524-68e545164da2.png)

2. El campo de "Depreciada" solo debe ser marcado cuando el api que consume tambien está depreciado.

**Comment by iMrJulian** [comment]
Se hizo revisión y modificación, agregando elementos como un resumen, link de autenticación con su respectivas correcciones y se reorganizo la información dentro de cada hoja correspondiente a una api depreciada para facilitar la legibilidad.

V2: https://docs.google.com/spreadsheets/d/14mORmhV7_eAZ8xB1XN02JPl_e6dieH6aWk6gwDB1BMo/edit?usp=sharing

**Comment by a52290451** [comment]
Se valida formato preliminar de conexiones entre APIs
