### ISSUE TITLE
Creación de grafo v1 de conexiones entre APIs - oikos_crud_api, core y admnistrativa_jbpm

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#33]
Empleando la herramienta Bokeh y NetworkX de Python, elaborar el mapa de conexiones entre APIs a través del consumo de servicios expuestos, mediante un grafo en el cual se realicen las siguientes especificaciones por nodo:

1. Nombre.
2. Puerto.
3. Listado de servicios.
4. Link intranet en ambiente de pruebas.
5. Link intranet en ambiente de producción.
6. Link autenticación.
7. Link Repositorio.
8. Link formato excel con conexiones - modo lectura.

**Criterios de aceptación**

- [x] Carga de archivos de desarrollo en repositorio (pendiente)
- [x] Lineamiento para ejecución de programa, con el fin de visualizar el mapa de conexiones.
- [x] Pruebas de funcionamiento.

**Comment by iMrJulian** [comment]
# Mapa de conexiones

Se debe instalar las librerías necesarias en este caso

- Bokeh
- Networkx
- Matplotlib

Para ello se instala utilizando

```ruby
pip install bokeh
pip install networkx
pip install matplotlib
```
Para correr el programa

```ruby
py main.py
```

**Comment by a52290451** [comment]
Queda pendiente adjuntar evidencia de las pruebas realizadas para cerrar issue.

**Comment by iMrJulian** [comment]
# Pruebas

## Inicio

![image](https://user-images.githubusercontent.com/36264252/197895995-7621d8fd-245a-4ca4-bcbf-0b34fba446f5.png)

**Comment by a52290451** [comment]
Se validan pruebas realizadas.
