### ISSUE TITLE
Completar formato de ruta de migración de servicios

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#35]
Se requiere completar formato de ruta de migración de servicios en APIs depreciadas, teniendo en cuenta la información registrada en los formatos individuales de conexiones por API y en el análisis recopilado de las diversas dependencias.

**Criterios de aceptación**

- [x] Reunión técnica con equipo de soporte de segundo nivel.
- [x] Formato completo con ruta de migración de servicios.

**Comment by iMrJulian** [comment]
Se completa la v1 de la ruta de migración de servicios

https://docs.google.com/spreadsheets/d/1_5Hnz0lDWbOYxA5hB_S7DfTuyPVkj9BJDtDWHiCiIRw/edit?usp=sharing
