### ISSUE TITLE
Análisis y planeación, Firma electrónica

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#39]
Se requiere implementar análisis y planeación para desarrollar funcionalidad de firma electrónica.

**Criterios de aceptación**

- [x] Flujo de actividades discriminado por componentes, APIs o sistemas onvolucrados.
- [x] Historias de usuario.

Nota: tener en cuenta el análisis desarrollado en #37 y [gestor_documental_mid#9](https://github.com/udistrital/gestor_documental_mid/issues/9)

**Comment by a52290451** [comment]
Se inicia proceso de análisis a través de diagrama de flujo de actividades para firma electrónica:
https://drive.google.com/file/d/1sq9J4dsgxRtzCcGw8y4lD6ygwJ4w1-bh/view?usp=sharing

La creación del flujo se llevo a cabo en 2 horas.

Queda pendiente su validación por parte del Gerente de Proyectos. @ndmc98

**Comment by ndmc98** [comment]
Revisado y validado, quedando atento a los posibles cambios mencionados.

**Comment by a52290451** [comment]
Se culmina proceso de análisis y planeación.
