### ISSUE TITLE
HU2 - 1 - Creación de servicio "store_document"

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#40]
Se requiere crear servicio con el nombre "store_document" en el Gestor Documental que permita almacenar un documento sin firmar en la base de datos.

Ruta sugerida: http://0.0.0.0:8080/v1/document/store_document

Observaciones:
1. Se debe almacenar la información de metadatos (en caso de que la petición reciba metadatos) en el API documentos_crud según el tipo de documento.
2. El documento físico debe almacenarse en NUXEO, creando un nuevo espacio.

**Criterios de aceptación**

- [x] Creación de rama Feat para nuevo servicio.
- [x] Desarrollo de nuevo servicio.
- [x] Commit en rama feat. 
- [x] Pull request en rama Develop
- [x] Pull request en ambiente de pruebas: "rama release". - Requiere aprobación.
- [x] Pruebas funcionales.
- [x] Check-list para despliegue en ambiente de producción.
- [x] Pull request en ambiente de producción: "rama master". - Requiere aprobación.
- [x] Estabilización del API.

Nota: tomar como referencia el archivo con [historias de usuario](https://docs.google.com/spreadsheets/d/1-6uz2aOsjtr3Ym1RhXU2tOspwlmS0qVU/edit#gid=1984585544) y sus respectivas variables, y el [documento de referencia](https://docs.google.com/document/d/1ETG2KtDpNXN8hTyjDIe-VkVJ9gGFqzaC/edit) para el API gestor_documental_mid.

**Comment by iMrJulian** [comment]
Funcionamiento del store_document en local
![image](https://user-images.githubusercontent.com/36264252/198996521-e460fe89-bee2-44c9-824b-31ba6a1dc322.png)

**Comment by a52290451** [comment]
Pull request: https://github.com/udistrital/gestor_documental_mid/pull/28

**Comment by a52290451** [comment]
Pull request a Release: https://github.com/udistrital/gestor_documental_mid/pull/30

**Comment by a52290451** [comment]
[Formato CheckList.docx](https://github.com/udistrital/autenticacion_mid/files/9903660/Formato.CheckList.docx)

**Comment by iMrJulian** [comment]
Checklist del servicio store_document

https://docs.google.com/document/d/1ne8hXGweD_SGg-xxthsv3Kqx7Iv5IP7P/edit?usp=sharing&ouid=118160889227965868747&rtpof=true&sd=true

**Comment by iMrJulian** [comment]
# Pruebas en release 

## Prueba 1

Guardar documento con el servicio POST store_document del gestor_documental_mid
![image](https://user-images.githubusercontent.com/36264252/199351153-4f61c6e4-e6eb-46e1-ab5a-740582324e3d.png)

Una vez se hace la carga del documento se obtiene el id y el uid

- **uid:** d271f130-1e1d-401a-ac72-3916ec9eb4d3
- **id:** 147008

Verificación del documento con el uid con el servicio GET document del gestor_documental_mid
![image (1)](https://user-images.githubusercontent.com/36264252/199351568-2cc347f9-a5b1-45f7-9a07-3e3a4db4b905.png)

Verificación de que el documento se encuentre cardado en el documentos_crud con su servicio documento y el id del archivo
![image](https://user-images.githubusercontent.com/36264252/199351787-5811936f-2c56-45a5-8fbe-c737bd00bde8.png)

## Prueba 2 sin metadata

Guardar documento con el servicio POST store_document del gestor_documental_mid
![image](https://user-images.githubusercontent.com/36264252/199352050-1570637c-ce2e-4621-b823-766dee00d8e0.png)

Una vez se hace la carga del documento se obtiene el id y el uid

- **uid:** c4eefbaf-1083-4b10-a419-f7b510a4b1e6
- **id:** 1470011

Verificación del documento con el uid con el servicio GET document del gestor_documental_mid
![image](https://user-images.githubusercontent.com/36264252/199352421-e00aef3b-73e2-4016-9919-883dc897c42f.png)

Verificación de que el documento se encuentre cardado en el documentos_crud con su servicio documento y el id del archivo
![image](https://user-images.githubusercontent.com/36264252/199352489-ada3e085-b971-42cc-902a-991e0aef58c4.png)

**Comment by a52290451** [comment]
Se validan pruebas funcionales realizadas.

**Comment by iMrJulian** [comment]
# Verificación de despliegue

## Prueba con metadatos

Guardar un documento con el servicio store_document
![image](https://user-images.githubusercontent.com/36264252/199835925-3b10b0b6-1727-4cf8-a0bc-127e9bd9628f.png)

Una vez se hace la carga del documento se obtiene el id y el uid

- **uid:** 50d876e2-fb9f-4ccb-83d3-cd13746a166a
- **id:** 203634

Verificación del documento con el uid dentro del gestor_documental
![image](https://user-images.githubusercontent.com/36264252/199836332-f4c518e4-7adf-4796-9ecd-06b15db8b79e.png)

Verificación del documento con el uid dentro de documentos_crud
![image](https://user-images.githubusercontent.com/36264252/199837270-08d5b66c-22ee-41f0-9ad0-f3a753c0901c.png)

## Prueba sin metadatos

Guardar un documento con el servicio store_document
![image](https://user-images.githubusercontent.com/36264252/199837542-ff4d95f9-b43c-4544-82a2-3cee3b199bc8.png)

Una vez se hace la carga del documento se obtiene el id y el uid

- **uid:** 0d4c3ab9-74ed-4518-a836-32eb35d447d4
- **id:** 203638

Verificación del documento con el uid dentro del gestor_documental
![image](https://user-images.githubusercontent.com/36264252/199837655-ef5aecd1-d1a2-40fa-afd1-bb48a7687a96.png)

Verificación del documento con el uid dentro de documentos_crud
![image](https://user-images.githubusercontent.com/36264252/199837753-fee8c74b-e0b6-49d8-9367-49b250f9c6d1.png)
