### ISSUE TITLE
Apropiación de generalidades: API gestor_documental_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#41]
Se requiere realizar la apropiación de generalidades con respecto al API gestor_documental_mid de acuerdo a las siguientes consideraciones:

1. Se debe clonar repositorio en local y comprobar su funcionamiento con peticiones a través de sus diferentes servicios.
2. Se debe comprobar el funcionamiento de documentos_crud en cuanto a la consulta y almacenamiento de metadatos.
3. Se requiere comprobar el funcionamiento de NUXEO en cuanto a la consulta y almacenamiento de documentos físicos y metadatos generados.
4. Revisar documentación del gestor_documental_mid.
5. Análisis de manipulación de documentos en base 64 con python para alteración de información. Tomar como referencia lo desarrollado en fases anteriores.

Observaciones:
1. Consultar credenciales para acceso a NUXEO con Cristian Alape.

**Criterios de acpetación**

- [x] Trazabilidad de cumplimiento de cada punto señalado, registrando a detalle lo realizado con descripción evidencia visual.

**Material de apoyo**
1. [Documentación y guía.](https://docs.google.com/document/d/1ETG2KtDpNXN8hTyjDIe-VkVJ9gGFqzaC/edit)
2. [Acta de entregable v1.](https://docs.google.com/document/d/1zvx6mWXI8Gy5Ad_4rbjSk5rb-o_IQ0F6/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true)

**Comment by iMrJulian** [comment]
# Apropiación

1. Se debe clonar repositorio en local y comprobar su funcionamiento con peticiones a través de sus diferentes servicios.

![image](https://user-images.githubusercontent.com/36264252/197901328-08b6e16d-8aa7-4ba2-bd1b-f004225e7fb3.png)

**Comment by a52290451** [comment]
Se requiere adjuntar evidencia de las subtareas realizadas.

**Comment by iMrJulian** [comment]
# Apropiación

### Se clona el repositorio del [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid)
![image](https://user-images.githubusercontent.com/36264252/197901328-08b6e16d-8aa7-4ba2-bd1b-f004225e7fb3.png)

### Correr la api del [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid)
![image](https://user-images.githubusercontent.com/36264252/198295521-d3587895-e9eb-4f0b-82b9-3a24f489a025.png)

### Probar su funcionamiento [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid)
Get /
![image](https://user-images.githubusercontent.com/36264252/198417149-4dd802c8-570a-4abc-a82e-4d351add595c.png)

Post /upload/{id} con un documento prueba en base 64
![image](https://user-images.githubusercontent.com/36264252/198299704-3d5b0b19-3fdf-45fc-8d17-a3e95153db38.png)

Get /upload/{id} con el documento prueba cargado anteriormente
![image](https://user-images.githubusercontent.com/36264252/198302111-045e9c56-5fb5-45ae-927d-5fd2b4404412.png)

Se prueba el funcionamiento de documentos_crud con el documento recien creado en la prueba de Post /upload/{id}
Get pruebasapi.intranetoas.udistrital.edu.co:8094/v1/tipo_documento/{id}
![image](https://user-images.githubusercontent.com/36264252/198417343-a7960e87-cac9-46a4-b5bf-3f8df0bc989e.png)

Insertar metadatos en un documento a partir de la obtención de el desde nuxeo, para luego insertarlo como propiedades del mismo en base64 a partir de un encoded, tomandolo como un diccionario donde tiene llave valor.
![image](https://user-images.githubusercontent.com/36264252/198588803-7a3a916a-9165-48aa-964c-da5a504f860d.png)

El gestor_documental_mid ya esta haciendo un proceso de firma electronica, generandola con la libreria Cryptography a partir de la generación de una llave privada y donde el metodo .sign de esta llave privada, crea la firma electronica sin necesidad de obtener el hash primero.
![image](https://user-images.githubusercontent.com/36264252/198616727-38844e7b-4a01-47ae-8c82-e78282363178.png)

Adicionalmente se encontro que el gestor documental no esta estampando la firma, si no que la pasa como metadata del documento.
![image](https://user-images.githubusercontent.com/36264252/198617573-c1d8bcad-ce65-4415-a5b2-6d20a1a36d99.png)
