### ISSUE TITLE
HU2 - 2 - Creación de Mockups para firma electrónica, sus componentes y ubicación en el documento.

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#42]
Se requiere elaborar Mockups para la firma electrónica de acurdo a las siguientes instrucciones:

1. Listar componentes de la firma electrónica.
2. Propuesta visual para firma electrónica que contenga los componentes señalados.
3. Propuesta de ubicación de firma electrónica en [Documento_Anexo](https://github.com/udistrital/autenticacion_mid/files/9853987/011600d7-62e4-4e5e-9b0d-fbcedf360b1f.pdf).

**Criterios de aceptación**

- [x] Listado de componentes de la firma electrónica.
- [x] Mockup de firma electrónica.
- [x] Documento con estampado de firma electrónica.
- [x] Validación de componentes, mockups y ubicación.

**Comment by iMrJulian** [comment]
## Posibles componentes de una firma electrónica

### Indispensables

- **Firma electrónica:** Código hash del documento encriptado con llave privada.
- **Fecha:** en que se completo la firma y el documento quedo cerrado.

### Agregan valor a la firma
- **Nombre:** Nombres y apellidos del firmante.
- **Identificación:** Identificación única del firmante
- **Tipo de documento:** Información acerca del documento que se esta firmando.
- **Nombre del documento:** Información acerca del documento que se esta firmando.
- **Dirección ip:** Dirección ip del firmante al momento de validar y aceptar el documento
-

**Comment by iMrJulian** [comment]
## Ejemplos 

[Ejemplo1.pdf](https://github.com/udistrital/autenticacion_mid/files/9903775/Ejemplo1.pdf)
[Ejemplo2.pdf](https://github.com/udistrital/autenticacion_mid/files/9903777/Ejemplo2.pdf)

**Comment by a52290451** [comment]
Queda pendiente la validación de mockups, elección de tipo de firma y ubicación de firma electrónica por parte de los interesados.

**Comment by a52290451** [comment]
De acuerdo a lo señalado, se opta por utilizar la siguiente firma:

![image](https://user-images.githubusercontent.com/36229498/200008317-1b53cc73-dc69-4172-b03b-0fbf0fa3a3ba.png)
