### ISSUE TITLE
HU2 - 2 - Análisis para creación de firma electrónica

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#44]
Se requiere implementar análisis con respecto a la creación de una firma electrónica a partir de un documento en base 64 y sus metadatos.

Se debe identificar si el calculo del código hash es con base en el documento fisico y sus metadatos o solo en el documento. Ademas, se debe especificar el procedimiento necesario para encriptar y desencriptar el código hash para la generación de la firma electrónica.

**Criterios de aceptación**

- [x] Documento con resultado del análisis realizado en el cual se menciona el procedimiento a seguir.

**Comment by iMrJulian** [comment]
Se realiza un análisis detallado sobre la implementación de la firma electrónica y las herramientas necesarias para hacerlo e implementarlos en el gestor_documental_mid

V1: https://docs.google.com/document/d/1UpDnH6Sdy5TIRfRMuPlCLQX4PpWOpm5XtqmAtYtK2uM/edit

**Comment by a52290451** [comment]
Se aprueba análisis realizado en documento "FIRMA ELECTRÓNICA", así como las soluciones propuestas
