### ISSUE TITLE
Completar formato excel de conexiones por API para APIs con nivel 2 de prioridad.

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#49]
Se requiere crear y completar el formato de conexiones de cada API a ser depreciada, tomando como referencia el formato estandar ubicado en #29.

APIs:

- Documentos (documentos_crud)
- ResolucionesDocentesMID
- sesiones_crud
- titan_api_crud
- titan_api_mid

**Criterios de aceptación**

- [x] Catalogo de conexiones por API.

**Comment by iMrJulian** [comment]
Se completa el formato con apis a deprecar de 2 y 3 nivel

https://docs.google.com/spreadsheets/d/14mORmhV7_eAZ8xB1XN02JPl_e6dieH6aWk6gwDB1BMo/edit?usp=sharing
