### ISSUE TITLE
Creación de grafo v2 de conexiones entre APIs, incluyendo APis depreciadas de nivel 2.

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#50]
Empleando la herramienta Bokeh y NetworkX de Python, elaborar el mapa de conexiones entre APIs a través del consumo de servicios expuestos, mediante un grafo en el cual se realicen las siguientes especificaciones por nodo:

1. Nombre.
2. Puerto.
3. Listado de servicios.
4. Link intranet en ambiente de pruebas.
5. Link intranet en ambiente de producción.
6. Link autenticación.
7. Link Repositorio.
8. Link formato excel con conexiones - modo lectura.

Las APIs a ser incluidas son:

- Documentos (documentos_crud)
- ResolucionesDocentesMID
- sesiones_crud
- titan_api_crud
- titan_api_mid

**Criterios de aceptación**

- [x] Carga de archivos de desarrollo en repositorio (pendiente)
- [x] Lineamiento para ejecución de programa, con el fin de visualizar el mapa de conexiones.
- [x] Pruebas de funcionamiento.

**Comment by iMrJulian** [comment]
# Mapa de conexiones

Se debe instalar las librerías necesarias en este caso

- Bokeh
- Networkx
- Matplotlib

Para ello se instala utilizando

```ruby
pip install bokeh
pip install networkx
pip install matplotlib
```
Para correr el programa

```ruby
py main.py
```
[MapaConexionesV2.zip](https://github.com/udistrital/autenticacion_mid/files/10295256/MapaConexionesV2.zip)

**Comment by iMrJulian** [comment]
# Pruebas

## Inicio

![image](https://user-images.githubusercontent.com/36264252/209342490-071d2d51-954c-429e-824e-2c9dc3778548.png)

## Seleccionar un nodo

![image](https://user-images.githubusercontent.com/36264252/209342570-c622362a-f8e2-471f-b9e4-456287aa5102.png)

## Seleccionar un nodo cuando ya se ha seleccionado uno previamente

![image](https://user-images.githubusercontent.com/36264252/209342658-0e8230c9-4a4c-4296-b226-583bd15a7bca.png)

## Deseleccionar

![image](https://user-images.githubusercontent.com/36264252/209342766-bc9ab8d3-0b18-4d80-a1bd-b89159bbcbd5.png)

## Mover grafo

![image](https://user-images.githubusercontent.com/36264252/209342879-c394d967-6fa3-416c-b026-a8f7d69c684e.png)

## Zoom

![image](https://user-images.githubusercontent.com/36264252/209343013-5ca324f8-3a1f-480c-9ecb-4f8237bbc93b.png)

## Reset

![image](https://user-images.githubusercontent.com/36264252/209343063-e8fd9619-3217-4444-a3ac-bf6ad7712e96.png)

## Guardar

![image](https://user-images.githubusercontent.com/36264252/209343108-b7c0f039-3c36-4509-bfb6-72fef4c44689.png)
