### ISSUE TITLE
Análisis - conexión con gestor_documental_mid para firma electrónica

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#58]
Se requiere evaluar desde que punto se debe realizar la conexión con el gestor_documental_mid.

Se requiere evaluar si es viable implementar la firma electrónica en este sistema y de que forma se realizaría, teniendo en cuenta que los contratistas solo podrán descargar la certificación, pero no podrán generarla.

**Criterios de aceptación**

- [x] Documento con análisis y planeación de implementación requerida.

**Comment by iMrJulian** [comment]
Se realiza un análisis de la viabilidad de la adaptación del api evaluacion_cliente, encontrando que es viable y como hacerlo

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/jdrinconc_udistrital_edu_co/ERkKrRqc9LtDmqQfRSXQRnsBXugsn22ChXrZSgVa_FRBnQ?e=r0FOJH

**Comment by a52290451** [comment]
Se relaciona "análisis de APIs depreciadas", realizado por otros equipos de inversión:

1. https://docs.google.com/spreadsheets/d/1NUGxIB2OFe56SNgtihhYNh7kEFRblh9u2lsuNtxIV_k/edit?pli=1#gid=0
2. https://docs.google.com/spreadsheets/d/1bJIC0k-JNnwTEudaF5QyiLn7Pc3Zo_mScKc4rNKKjfo/edit#gid=0
