### ISSUE TITLE
Creación de API sideap_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_mid#60]
Se requiere implementar el API sideap_mid para establecer la interoperabilidad con los servicios ofrecidos por el SIDEAP asociados con información básica,  información de hoja de vida y documentos de soporte relacionados.

**Especificaciones técnicas**

- documento técnico proporcionado por el SIDEAP que resume los pasos necesarios para establecer la conexión con el servidor de pruebas de la entidad.
- documento de análisis de información en común entre el sistema ÁGORA de la Universidad Distrital y SIDEAP.

**Sub Tareas**

- [x] Creación y ajuste del repositorio.
- [x] Creación de API en local, con estructura base de API MID (tomar como referencia el API cumplidos_dve_mid en sus primeros commits).
- [x] Creación de controlador y helpers para consumir datos basicos de SIDEAP según instructivo.
- [x] Creación de controlador y helpers para consumir datos de hoja de vida de SIDEAP según instructivo.

**Criterios de aceptación**

- [x] la información básica de una persona puede ser consultada a través del API sideap_mid mediante su cedula de ciudadanía.
- [x] la información de hoja de vida de una persona puede ser consultada a través del API sideap_mid mediante el id del sideap que se obtiene al consultar la información básica.

**Requerimientos**

- [x] repositorio guía para creación de repositorio sideap_mid.
- [x] documentación de conexión con sideap.

**Dependencias**

- SIDEAP

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Manual técnico - Conexión SIDEAP:
[2023-04-24 A-TIC-FM-013 EP_002_HU_001_UNIV_DIST_V1.0.docx](https://github.com/udistrital/autenticacion_mid/files/11336892/2023-04-24.A-TIC-FM-013.EP_002_HU_001_UNIV_DIST_V1.0.docx)

**Comment by a52290451** [comment]
Endpoints de conexión

1. Datos Básicos: http://preproduccion.serviciocivil.gov.co:8585/sideapInteroperabilidad/webresourcesJSON/udistrital/obtenerDatosBasicosUDISTRITAL
2. Hoja de vida: http://preproduccion.serviciocivil.gov.co:8585/sideapInteroperabilidad/webresourcesJSON/udistrital/obtenerHojaVidaUDISTRITAL

Para los datos de consulta y clave de conexión, revisar correo relacionado

**Comment by a52290451** [comment]
Repositorio para sideap_mid: https://github.com/udistrital/sideap_mid

**Comment by a52290451** [comment]
Realizar pruebas en local

**Comment by ludwinggsanchez** [comment]
![image](https://user-images.githubusercontent.com/35748918/235706119-c4d96d31-c56d-4d27-9f91-677b11ad74f7.png)
