### ISSUE TITLE
Correcciones módulo evaluaciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#65]
Se requieren realizar ajustes sobre el sistema de evaluación para poder entregar el producto.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama master.

**Sub Tareas**

- [x] Adición de perfil supervisor.
- [x] Ajuste en la consulta de contratos a evaluar, restringiendo la consulta de contratos a cargo del supervisor.
- [x] Creación o adición de rol de compras, para certificaciones contractuales.
- [x] Restringir certificación contractual para contratos de "Sección compras".
- [x] Para los certificados emitidos por sección de compras emitirse con el nombre de la dependencia y los datos de la sección "Jefe", "firma jefe" y reemplazo de OAJ por Sección de compras.
- [x] Quitar acceso a consulta y edición de evaluaciones rol "Jurídica".
- [x] Corregir el nombre de la persona que ingresa al sistema en el apartado "Elaborado por", en certificaciones contractuales.

**Criterios de aceptación**

- [x] Se evidencia desde el rol de supervisor que solo me cargan aquellos contratos que están bajo mi cargo.
- [x] Para emisión de certificaciones contractuales aquellas que sean desde sección de compras se evidencia que la plantilla cambia los campos que relacionan la OAJ por la sección de compras.
- [x] Desde el rol "Jurídica" y "Asistente jurídica", no se puede editar ninguna evaluación.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Pendiente confirmar los permisos para el módulo de evaluación para el ro **Ordenador del gasto**

**Comment by ludwinggsanchez** [comment]
Qué tipos de contratos puede certificar el rol de **Jurídica**

**Comment by milo19980525** [comment]
Los contratos de sección de compras son: Órdenes de compra y Órdenes de servicio

**Comment by milo19980525** [comment]
La imagen del jefe de compras fue compartido al chat de Teams interno del ingeniero @ludwinggsanchez. De igual manera se confirma que su nombre es: RAFAEL ENRIQUE ARANZALEZ GARCIA.

**Comment by ludwinggsanchez** [comment]
Actualmente el rol ASISTENTE_COMPRAS no tiene permisos para generar certificación contractual

**Comment by ludwinggsanchez** [comment]
Confirmar qué se debe poner para las certificaciones emitidas por la sección de compras en este caso:

![image](https://github.com/udistrital/autenticacion_mid/assets/35748918/36f22896-a799-46c9-813c-c4928cfc1457)

**Comment by ludwinggsanchez** [comment]
Indicar el correo que debe agregarse a la certificación

**Comment by ludwinggsanchez** [comment]
Certificación contractual emitida por sección de compras:

[Certificacion_1421__830127933_contractual (4).pdf](https://github.com/udistrital/autenticacion_mid/files/11703997/Certificacion_1421__830127933_contractual.4.pdf)

**Comment by ludwinggsanchez** [comment]
Árbol de permisos del sistema

![image](https://github.com/udistrital/autenticacion_mid/assets/35748918/7d1985b2-11ca-460b-9fdc-4c6b0b0a7fc7)

Roles registrados

![image](https://github.com/udistrital/autenticacion_mid/assets/35748918/eccb6fd9-a72e-47d6-a84b-113a48fb53f3)

**Comment by milo19980525** [comment]
@a52290451 Se encuentra probando los ajustes realizados, sin embargo el desarrollo está finalizado.

**Comment by a52290451** [comment]
Validación de funcionalidades implementadas:

1. Ajuste en la consulta de contratos a evaluar, restringiendo la consulta de contratos a cargo del supervisor.

**Resultado**:

Empleando el usuario pruebasoas3 que posee los siguientes roles:

COORDINADOR_PREGRADO
COORDINADOR_POSGRADO
ASISTENTE_JURIDICA
SUPERVISOR

Es posible validar que el menú "Evaluación" esta disponible para el rol de Supervisor.

Además, este menú también queda habilitado para el rol "Ordenador del gasto".

2. Certificaciones contractuales para Sección de compras.

3. Quitar acceso a consulta y edición de evaluaciones rol "Jurídica"

Empleando el usuario pruebasoas2 que posee los siguientes roles:

GESTOR_NOVEDADES
ASISTENTE_JURIDICA
ADMINISTRADOR_RESOLUCIONES
ADMIN_PERSEO
ADMIN_CONTABILIDAD
ADMIN_POLUX
ASISTENTE_DECANATURA

Se confirma que el rol "ASISTENTE_JURIDICA" solo tiene permisos para ingresar al menú "Certificaciones contractuales":

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/33fadccb-f3c3-4890-a557-e26f8027c34d)

4. Eliminar contratos CPS de los contratos disponibles para su evaluación en el menú "Evaluación".

Al realizar la búsqueda con el contrato 1285 y otros contratos adicionales, solo aparecen contratos asociados a proveedores.

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/71de44c5-ff7e-40c2-a6c1-78ce623c6c0a)

Con esto se valida la corrección realizada.
