### ISSUE TITLE
Diseño módulo de verificación

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#66]
Se requiere la creación de mockup relacionado con una vista de verificación de documentos estampados con firma electrónica

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama develop.

**Sub Tareas**

- [ ] Diseño y creación de mockup sobre vista de validación de documento firmado electrónicamente.

**Criterios de aceptación**

- [ ] Se puede consultar por el id de la firma electrónica el documento relacionado a esta, por lo que la interfaz permite consultar por este identificador y se visualiza el documento almacenado en el gestor documental.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
**Logo:**

![image](https://github.com/udistrital/autenticacion_mid/assets/35748918/9593781e-adab-40a6-9246-81687fd6b395)

**Comment by ludwinggsanchez** [comment]
Mockup:

[mockupVerificacion.pdf](https://github.com/udistrital/autenticacion_mid/files/11741374/mockupVerificacion.pdf)

**Comment by milo19980525** [comment]
Perfecto, gracias.
