### ISSUE TITLE
Revisión X-ROAD y Furag

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#68]
Se requiere revisar en el estado del arte todo lo relacionado con X-ROAD y Furag, plataforma gubernamental que se ha implementado en diferentes países para integrar e interoperar de manera segura cada uno de los servicios o información transversal al estado.

**Especificaciones técnicas**

- Revisar los requisitos técnicos.

**Sub Tareas**

- [x] Revisión del estado del arte sobre las dos aplicaciones mencionadas previamente.
- [x] Analisis de casos de implementación externo (internacional) y adelantos nacionales.
- [x] Revisión de requerimientos de capacida computacional y humanos para poder llevar a cabo una implementación en la universidad.
- [x] Revisión de requisitos y propuestas de seguridad por cada una de las aplicaciones.
- [x] Tabla comparativa entre ambas aplicaciones, de igual manera ventajas y desventajas.
- [x] Hacer un listado de posibles integraciones futuras.

**Criterios de aceptación**

- [x] Revisión del estado del arte
- [x] Documentación del issue y diligenciamiento de lo encontrado en un documento word

**Requerimientos**

- [x] Ninguna

**Dependencias**

- Ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Se da inicio a la investigación, empezando con la tecnología X-ROAD. A continuación se presenta el documento relacionado:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ETAU6u2C4ShPgyPyCB_YF9wBWXQnlcY5YuFt63DVmPx9rQ?e=iepiSB

**Comment by a52290451** [comment]
Se finaliza investigación acerca de X-ROAD y FURAG.

**Comment by a52290451** [comment]
Es importante tener en cuenta que la implementación de X-Road en Colombia se encuentra en una fase de establecimiento, y se espera que siga evolucionando y expandiéndose en el futuro. El Ministerio de Tecnologías de la Información y las Comunicaciones en apoyo de la Agencia Nacional Digital se encuentran en la implementación de un piloto de intercambio de información entre el sector público y privado a través de la plataforma XROAD, con el fin de evidenciar las oportunidades de esta solución tecnológica para la generación de valor tanto en el sector público como privado. Esta acción inició en el año 2022 y finalizará en el año 2023. 

No hay mayor información del estado actual de X-Road en Colombia, por lo que no se puede proponer una estrategia para ingresar al ecosistema.

Se recomienda contactar con MinTIC para conocer su estado y ver de que forma la OAS puede unirse.
