### ISSUE TITLE
Prueba de funcionamiento Servicio AWS X-Ray conexión entre dos APIs

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#71]
Se requiere realizar la prueba de conexión entre dos APIs utilizando el servicio de X-Ray.

1. El modulo debe mostrar en tiempo real el estado en que se encuentran esas dos APIs.
2. Se requiere visualizar gráficamente las conexiones que existen entre las dos APIs y las peticiones que son utilzadas entre estas.

**Especificaciones técnicas**

- Se debe continuar con el issue #67 

**Sub Tareas**

- [x] Revisión y corrección del paso del contexto entre dos APIs.
- [x] Validación del gráfico que denota la conexión entre APIs.

**Criterios de aceptación**

- [x] El gráfico de X-Ray muestra como segmentos a las APIs de cumplidos_dve_crud y cumplidos_dve_mid, las aristas entre estos representan las peticiones que se hacen entre estas.

**Requerimientos**

- [x] Acceso total a servicio X-Ray y su complemento en CloudWatch en AWS.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Se logra realizar la conexión entre 2 APIs empleando el ID de la traza y del segmento original de la API que inicia los llamados a las demás APIs:

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/66bb112e-130c-437a-8209-e27a20ab0962)

Como se evidencia en la imagen, se refleja la conexión entre el API cumplidos_dve_mid y cumplidos_dve_crud. Esta se logra, capturando desde cumplidos_dve_crud, el ID de la traza y el segmento que se iniciaron en cumplidos_dve_mid he igualándolos a los valores que se generan en  cumplidos_dve_crud.

Con esta tarea completa, queda pendiente limpiar el código generado y simplificar el desarrollo en funciones comunes, así como replicar lo implementado para todos los controladores que posean las APIs.
