### ISSUE TITLE
Análisis de herramientas para automatizar código

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#75]
Se requiere investigar que herramientas existen en el mercado que permiten la generación de código automatizada.

**Especificaciones técnicas**

- Los lineamientos de la oficina se encuentran disponibles en: https://github.com/udistrital/lineamientos_oas.

**Sub Tareas**

- [x] Investigar que herramientas de manera genérica permiten implementar automatización de código, listarlas y realizar una comparativa entre estas (características principales, ventajas y desventajas).
- [x] Filtrar entre las herramientas encontradas cuales de estas soportan Angular (¿Que versiones?), Vue JS, golang y python.
- [x] Tener en cuenta la manera de creación de APIs y clientes de la OAS, tratar de conseguir herramienta que a partir de un código base y parámetros definidos genere controladores, modelos y helpers de manera instantanea.

**Criterios de aceptación**

- [x] Se realiza la invesitgación pertinente a cada uno de los puntos y se documenta en el issue.
- [x] Se determinan que herramientas son más preponderantes frente a los requerimientos de la Oficina.

**Requerimientos**

- [x] Ninguno

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
**Investigación sobre Herramientas para automatización de código:**

**FRONTEND**

**Java Script**

1. **Angular JS**

- Angular CLI

2. **Viu JS**

- Viu CLI

3. **React**

- Create React App

4. **Generales**

- Yeoman
- Hygen

**BACKEND**

1. **GO**
2. **Python**

**Herramientas de Apoyo con IA**

1. **GitHub Copilot**
2. **Black Box**
3. **Codeium**
6. **CodeWhisperer**
7. **Tabnine**
8. **Codex**
9. **Intellicode**
10. **AskCode**

**Comment by milo19980525** [comment]
@a52290451  Realizar la presentación de las herramientas encontradas (al mismo estilo de X-Ray).

**Comment by a52290451** [comment]
Presentación de Herramientas para Automatización de Código:

https://gamma.app/docs/Herramientas-de-Automatizacion-de-Codigo-sf6x4to9ud76hyb
