### ISSUE TITLE
Corrección para toma de errores en las APIs e implementación de canaries

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#77]
Se requiere revisar la captura de errores a través de X-Ray revisando los mensajes de error arrojados por la respuesta obtenida al realizar el llamado. De igual manera se requiere una prueba de concepto de cannaries.

**Especificaciones técnicas**

- El último desarrollo relacionado con la implementación de X-Ray se encuentra en release para ambas APIs.
- Las tareas del presente issue salen de un análisis realizado en #73.

**Sub Tareas**

- [x] Verificar la coherencia de respuestas de solicitudes de APIs. En el caso de "cumplidos_dve_mid" algunas solicitudes en las cuales el código de respuesta debe ser 500, aparecen como 200.
- [x] Revisar implementación de GetRequestNew y funciones derivadas en el archivo "utilidades", cuando un endpoint no responde, no se realiza un manejo adecuado del error.
- [x] El error 404, no se puede capturar en los segmentos ya que su causa es a raíz de no encontrar el servicio señalado para el API en cuestión. Se debe buscar una forma de identificarlo sin alterar el código fuente de las APIs.
- [x] Implementación de cannaries con base en lo especificado en #73.

**Criterios de aceptación**

- [x] Se validan los requerimientos del issue y se da solución a la captura de dichos errores.
- [x] Se implementa una prueba de concepto de cannaries.
- [x] Se documenta el issue con el trabajo realizado.

**Requerimientos**

- [x] Acceso total a servicio X-Ray y su complemento en CloudWatch en AWS.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Verificar la coherencia de respuestas de solicitudes de APIs. En el caso de "cumplidos_dve_mid" algunas solicitudes en las cuales el código de respuesta debe ser 500, aparecen como 200.

En el archivo "utilidades" de "cumplidos_dve_mid" se realiza el ajuste de la función "ExtractData" para evaluar cuando el error devuelto por la función "GetJson" es diferente de "nil":

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/4d697f06-d611-4ca6-8c9e-5edcbb66029b)

De esta forma, cuando una sub consulta proveniente de los helpers, que se realiza hacia APIs externas devuelve un error de conexión, la consulta se maneja como un error de conexión con sus respectivos Panics. Anteriormente se manejaba con un estado 200 con data null, como si no se encontrara data para el registro referido, lo cual no es correcto.

Comportamiento anterior:

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/72abc379-0fd1-4563-a32f-810e3acb3c4b)

Comportamiento actual:

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/eb49971d-6981-4e86-85fd-eca0a95a4cd1)

**Comment by a52290451** [comment]
Se realiza la implementación de un canario que realiza diferentes peticiones a los servicios expuestos por "cumplidos_dve_mid". Sin embargo, no se ha logrado corregir su funcionamientod debido a problemas relacionados con la configuración de la VPC, para que pueda hacer peticiones directas a la API, sin necesidad de utilizar un token de autenticación.

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/2f35a00b-0e35-494b-93d5-789fec3fe353)

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/012eaca2-7d6d-468c-826f-220a9353706c)

Cuando se elimina la configuración de la VPC, el canario se ejecuta correctamente, pero se rechaza la conexión al endpoint señalado.

El problema actual radica en que no se reconoce la VPC en la configuración del canarie y, por lo tanto, no se ejecuta correctamente. Esto puede deberse a los grupos de permisos dispuestos para el canario con respecto al acceso a la VPC, datos de conexión de la VPC o configuraciones adicionales requeridas y no identificadas.

Actualmente el servicio se encuentra detenido y en revisión.

**Comment by a52290451** [comment]
PR desarrollo relacionado con AWS XRAY en APIs:

https://github.com/udistrital/cumplidos_dve_crud/pull/22

https://github.com/udistrital/cumplidos_dve_mid/pull/101

https://github.com/udistrital/utils_oas/pull/29

**Comment by a52290451** [comment]
Una vez desplegado en ambiente de pruebas, cuando se realizan peticiones a las APIs, estas quedan registradas en el mapa de servicios:

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/6382a42c-a6f7-4e1d-aae8-4c874dba4524)

**Comment by milo19980525** [comment]
Se está revisando el estado de los cannaries en el issue #78
