### ISSUE TITLE
Prueba de concepto herramienta de automatización de código

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#79]
Se requiere desarrollar una prueba de concepto para automatización de código empleando alguna de las herrmientas encontradas en #75.

**Especificaciones técnicas**

- La prueba de concepto se debe realizar con un proyecto con forma base de proyecto web (parte front). Además de una estructura para el black (mid y crud)
- Las herramientas identificadas en la issue #75 se deben utilizar para la prueba de concepto (por lo menos una).

**Sub Tareas**

- [x] Desarrollar una plantilla para un proyecto tipo front básico (escoga la estructura que más le convenga o que considere pertinente), definiendo los parámetros configurables la estructura de archivos pertinente y demás configuración posible.
- [x] Desarrollar una plantilla para un proyecto tipo back básico CRUD (escoga la estructura que más le convenga o que considere pertinente), definiendo los parámetros configurables la estructura de archivos pertinente y demás configuración posible.
- [x] Desarrollar una plantilla para un proyecto tipo back básico MID (escoga la estructura que más le convenga o que considere pertinente), definiendo los parámetros configurables la estructura de archivos pertinente y demás configuración posible.

**Criterios de aceptación**

- [x] Se crea una plantilla con parametros que dan como resultado la estructura base de un proyecto tipo front.
- [x] Se crea una plantilla con parametros que dan como resultado la estructura base de un proyecto tipo back (Mid).
- [x] Se crea una plantilla con parametros que dan como resultado la estructura base de un proyecto tipo front (Crud).

**Requerimientos**

- [x] Revisión y análisis de herramientas de automatización

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@a52290451 Por favor comentar lo adelantado en el issue.

**Comment by a52290451** [comment]
**Herramienta utilizada**

Para la automatización de código en la creación y refactorización de proyectos, se empleo Hygen, cuya investigación se encuentra en: #75 

**Creación de plantilla para API_MID en GO**

Para la creación de la plantilla API_MID se utilizo como punto de referencia la API **CUMPLIDOS_DVE_MID**. 
La implementación inicial deja como resultado la siguiente estructura de archivos fuente:

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/225fddde-5105-41c2-bb5a-de5b89989fba)

Los datos que se configuraron para que sean ingresados por parte del usuario y lograr un mayor nivel de personalización de la API generada son:

- goversion: versión de GO
- pgversion: versión de Postgres para el archivo docker-compose.yml
- dcversion: versión de docker-compose

Para la creación de la API se ejecuta el siguiente comando:

```shell
hygen api_mid_template with-prompt --appname api_mid_prueba
``` 

En donde:
- "api_mid_template" representa el generador.
- "with-prompt" representa una subdivisión al interior del generador.
-  --appname representa una acción (en este caso define una variable de entrada)
- api_mid_prueba representa el nombre de la variable, que equivale al nombre de la API

Luego se solicita que se ingresen los datos anteriormente mencionados:

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/56d0256d-d68a-4ad3-aeb7-b49bb4fd49f3)

Y, finalmente, de forma automática, se crea el directorio con el nombre de la API señalado, y en su interior todos los archivos correspondientes:

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/2c2529c7-d2f1-4eae-97f9-4e7df0a1c62e)

La vista final de la estructura de archivos de la nueva API queda de la siguiente manera.

![image](https://github.com/udistrital/autenticacion_mid/assets/36229498/4af25f01-1022-4ed9-9a72-00fb99f2bfe4)

Nota: cabe aclarar que, al finalizar la generación de los archivos, de igual forma se instrumentan una serie de comandos que generan archivos complementarios como "go.mod", "go.sum", "swagger.json", "swagger.yml" entre otros. Todo esto con el fin de lograr que la API quede lista para su ejecución.

**Creación de plantilla para API_CRUD en GO**



**Creación de plantilla para Nuevos Clientes en Angular JS y TypeScript**

**Comment by a52290451** [comment]
@milo19980525 Se requiere especificar Repositorio para cargar las plantillas creadas

**Comment by milo19980525** [comment]
@a52290451 porfa crear un nuevo repo para cada plantilla y subirlo allí, muy buen trabajo.

**Comment by a52290451** [comment]
**Creación de repositorios**

1. Repositorio para Plantilla API_MID: https://github.com/udistrital/plantilla_api_mid

2. Repositorio para Plantilla API_CRUD: https://github.com/udistrital/plantilla_api_mid

3. Repositorio para Plantilla de Nuevos Clientes: https://github.com/udistrital/plantilla_cliente_oas
