### ISSUE TITLE
Definición de lineamiento X-Ray y ajuste de cliente con hygen

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#85]
Se requiere definir el lineamiento de implementación de X-Ray para las APIs MID y CRUD de la OATI. Además, se debe actualizar la plantilla del cliente para que quede como lineamiento de la OATI.

**Especificaciones técnicas**

- Se debe definir el lineamiento de creación para los clientes de la OATI, a partir de la herramienta Hygen.
- Crear lineamiento para el uso de X-Ray en Api mid y crud.

**Sub Tareas**

- [x] Actualizar y optimizar la plantilla del cliente de plantilla base.
- [x] Integrar Hygen con Github en el repositorio de plantillas para el cliente.
- [x] Desarrollar un documento técnico para la implementación de nuevos repositorios tipo cliente a partir de la herramienta Hygen.
- [x] A partir del documento generado escribir el lineamiento en el repositorio: https://github.com/udistrital/lineamientos_oas.
- [x] Ajuste de utils para que tenga métodos más genericos para realizar peticiones desde la mayoría de apis mid.
- [x] Crear lineamiento para uso de X-ray en apis Mid y Crud (https://github.com/udistrital/lineamientos_oas.).

**Criterios de aceptación**

- [x] Se define el documento técnico asociado a la implemenatación de nuevos repositorios tipo cliente.
- [x] Se actualizan los lineamientos para creación de nuevos repositorios tipo cliente.
- [x] Se define lineamiento para uso de X-ray.

**Requerimientos**

- [x] Revisión y análisis de herramientas de automatización
- [X] Establecimiento de la herramienta de automatización y pruebas de concepto.
- [x] Prueba de concepto de X-Ray.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Para estandarizar la utilización de la librería 'request' en 'utils_oas', es necesario establecer una normativa, ya que cada API modifica los métodos predefinidos según su preferencia. Esto conlleva a que los métodos tengan la misma nomenclatura, pero varíen en los datos que reciben y devuelven.

**Comment by a52290451** [comment]
**Actualización de estado de actividades**

Se realiza la corrección de la plantilla "plantilla_cliente_oas" integrando cambios asociados a la inclusión de assets en el cliente recién creado y actualización del instructivo de instalación:

https://github.com/udistrital/plantilla_cliente_oas/pull/1



Se adjunta manual técnico para Creación de Clientes en Angular JS y TypeScript con plantillas de código:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESpe5eurOgJLoaT-EbeoiycBDN1p8_yiG-LdrFmGfjVWVA?e=FvacF2

Nota: el manual se encuentra terminado en su totalidad.

**Comment by a52290451** [comment]
Se crea PR para actualizar lineamientos asociados a la plantilla para la creación de Clientes en Angular JS y TypeScript con Hygen:

https://github.com/udistrital/lineamientos_oas/pull/42

**Comment by a52290451** [comment]
Se realiza la Revisión y Migración inicial de métodos de "Utilidades" en las APIs MID al paquete "utils_oas/request":

[Migración de Utilidades de APIS_MID.xlsx](https://github.com/udistrital/autenticacion_mid/files/13345469/Migracion.de.Utilidades.de.APIS_MID.xlsx)

Se han migrado:

- cumplidos_dve_mid
- resoluciones_mid_v2
- titan_api_mid
- sga_mid

En esta última se hace necesario revisar mas a profundidad su estructura ya que presenta varios archivos de utilidades y métodos repetidos.

**Comment by milo19980525** [comment]
@a52290451 por favor comentar estado de esta issue.

**Comment by a52290451** [comment]
**Actualización de estado de actividades**

1. Se realiza la actualización del paquete **"request"** en **"utils_oas"** refactorizando sus métodos para que sean genéricos y consumibles por cualquier API.

PR: https://github.com/udistrital/utils_oas/pull/35

**En este caso se debe tener en cuenta que, cuando se realice la aprobación del PR, los cambios quedaran de forma global. Esto quiere decir que, cuando una API actualice la versión de utils_oas, deberá también instrumentarse con AWS_XRAY.**

A la fecha, se han migrado y refactorizado 5 de las 35 APIs con las que cuenta la OATI, por lo que es una tarea que debe continuar.

**Comment by a52290451** [comment]
**Actualización de estado de actividades**

Se realiza la creación de lineamientos para la refactorización de APIs MID y CRUD con el fin de incluir el servicio de AWS X-Ray para el monitoreo de APIs:

https://github.com/udistrital/lineamientos_oas/blob/feature/XRay/generacion_de_apis/AWS_XRay.md

PR Master: https://github.com/udistrital/lineamientos_oas/pull/43
