### ISSUE TITLE
Documentación Final CORE

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#88]
Se requiere realizar los documentos finales "Diagnóstico" e "Informe final" para todos las funcionalidades desarrolladas y por desarrollar en el CORE.

**Especificaciones técnicas**

- El formato del informe diagnóstico se encuentra en: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcEzaU-TYfNMpdLTB7j9u5IB-pa9uKfFzPSdI-ANpHqThA?e=1l6H4s.
- El formato de infrome final: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfNyNLbkaFFFuqvSz0Qgte4BBWuLSjwTG4o_24-pvAdK7A?e=ytMggB

**Sub Tareas**

- [x] Con base en los formatos propuestos desarrollar los informes.

**Criterios de aceptación**

- [x] Se genera un diagnóstico final sobre los proyectos llevados a cabo en el CORE.
- [x] Se evidencia el informe final asociado a los proyectos del CORE.

**Requerimientos**

- [X] Formatos para desarrollar.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Se inicia con el informe de diagnostico de los desarrollos realizados en el CORE:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EXnVKJtW5NpJjy-GV0usvjwB40DPrSzLgsiNKVZnrWkI_g?e=N4zN1j

**Comment by a52290451** [comment]
**Actualización de estado**

Se finaliza el informe de diagnostico de los desarrollos realizados en el CORE, señalando en cada caso las oportunidades de mejora correspondientes.

**Comment by a52290451** [comment]
Se inicia con el informe final asociado a los proyectos del CORE:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESgIPWeZk9lFn46XltYz758BvRW6UXM9npwiYHnqepS7sw?e=dbSzc5

**Comment by a52290451** [comment]
**Actualización de estado**

Se culmina el informe final asociado a los proyectos del CORE, señalando en cada caso´:

1. Descripción del Hito.
2. Estado inicial.
3. APIs ajustadas.
4. Evidencia del Hito.
5. Cronograma de actividades.
6. Diagnostico final y oportunidades de mejora.

**Comment by milo19980525** [comment]
@a52290451 Muchas gracias por el excelente trabajo!
