### ISSUE TITLE
Revisión de APIs a ser depreciadas - 1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/autenticacion_mid#89]
Se requiere revisar el listado adjunto en especificaciones técnicas y verificar cuales son las APIs no se  deben depreciar o analizar. 

**Especificaciones técnicas**

- El documento relacionado a la depreciación de APIs corresponde a: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EfZVSP1VSotOjJwh1-k4XvgBnRcvu-dMTIMzxWWgjX5tBQ?e=MvD6Wv

**Sub Tareas**

- [x]  En el archivo con el listado de APIs relacionar aquellas que no se deben depreciar en la hoja "Revisión", con base en su manejo actual o que conozcan son fundamentales o utilizadas para la operación de alguno de los sistemas de la oficina.

**Criterios de aceptación**

- [x] Se relacionan en el listado de APIs aquellas que no se deben depreciar, colocando en la casilla de "Observaciones" por qué razón no se deben depreciar y la persona que lo verificó.
- [x] Se realiza comentario individual en el issue con el avance o terminación de la tarea.

**Requerimientos**

- [ ] Ninguno

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se realiza la actualización de información en base a cumplidos DVE.

**Comment by diagutierrezro** [comment]
Se agregan las apis que se usan en resoluciones V2 y polux

**Comment by ludwinggsanchez** [comment]
Se agregan apis requeridas en sistemas arka y evaluacion

**Comment by milo19980525** [comment]
@Yaov05, @JuanCamiloMartinezLopez y @edwargl7 por favor realizar el respectivo trabajo requerido.

**Comment by Yaov05** [comment]
Se agregan apis requeridas en sistema de novedades

**Comment by edwargl7** [comment]
Se agregan APIs requeridas en el SGA y SICIUD

**Comment by milo19980525** [comment]
Buen trabajo por parte de todos, gracias!
Por favor colocar el nombre tal cual como está el api en la hoja1 y rellenar en verde el nombre de las apis que ya revisaron en la hoja 1.

![image](https://github.com/udistrital/autenticacion_mid/assets/106636533/d450c7ad-8a01-4653-8a57-b5bf04349216)
